### ISSUE TITLE
Mas info 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SirWerto/Mi-intento-final-de-Travian#1]
Agrega mas info al readme. Ando buscando un serv de travian pra autohospedar

**Comment by SirWerto** [comment]
Subido el nuevo readme 7955ef61b0330ee416dbf5553ed40e0e3f51e703. No estoy pensando hacer un servidor si es lo que preguntas😔

**Comment by AnonymousWebHacker** [comment]
hahaa veo que hablas spanish no?,

**Comment by SirWerto** [comment]
Si:)

**Comment by AnonymousWebHacker** [comment]
Disculpa mi ignorancia, pero no entendi esto al final 
`MyTravian es un proyecto que intenta llenar el vacío entre identificar a los jugadores inactivos / vacas / granjas a mano y hacerlo con técnicas de aprendizaje automático.
`
o sea, sigo sin entender el objetivo del proyecto

**Comment by SirWerto** [comment]
Igual lo tengo que dejar un poco más claro en el readme. La idea es hacer un algoritmo que prediga que jugadores van a dejar de jugar y subirlo a la nube como herramienta para la comunidad de travian

**Comment by AnonymousWebHacker** [comment]
hahaha mucho mejor asi, espero que arregles tu readme , y gracias
